## Coding Exercise #0801

### 1. TensorFlow basics:

In [1]:
# Install once.
# !pip install tensorflow
# OR
# !pip install --user tensorflow-gpu

In [2]:
!pip install tensorflow

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\prati\\anaconda3\\Lib\\site-packages\\~umpy\\.libs\\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll'
Consider using the `--user` option or check the permissions.



  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.3
    Uninstalling numpy-1.22.3:
      Successfully uninstalled numpy-1.22.3


In [3]:
import tensorflow as tf
import numpy as np

C:\Users\prati\anaconda3\lib\site-packages\scipy\__init__.py:173: UserWarning: A NumPy version >=1.19.5 and <1.27.0 is required for this version of SciPy (detected version 1.18.5)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [4]:
tf.__version__

'2.3.0'

#### 1.1. Hello World!

In [5]:
hello = tf.constant("Hello World!")

In [6]:
hello

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello World!'>

#### 1.2. Creating tensors:

In [7]:
hello = tf.constant("Hello World!")                         # String.
const_scalar = tf.constant(7)                               # A scalar tensor.
const_matrix = tf.constant([[1,2], [3,4]])                  # A matrix tensor.
mat_fill = tf.fill((4,4),9)                                 # A 4x4 tensor filled with 9s.
mat_zeros = tf.zeros((3,3))                                 # A 3x3 tensor filled with 0s.
mat_ones = tf.ones((5,5))                                   # A 5x5 tensor filled with 1s.
mat_randn = tf.random.normal((3,3), mean=0, stddev=1.0)     # 3x3 random normal tensor.
mat_randu = tf.random.uniform((4,4), minval=0, maxval=1.0)  # 4x4 random uniform tensor.

In [8]:
my_ops=[hello, const_scalar, const_matrix, mat_fill, mat_zeros, mat_ones, mat_randn, mat_randu]
for op in my_ops:
    print(type(op))
    print('\n')
    print(op)
    print('\n')

<class 'tensorflow.python.framework.ops.EagerTensor'>


tf.Tensor(b'Hello World!', shape=(), dtype=string)


<class 'tensorflow.python.framework.ops.EagerTensor'>


tf.Tensor(7, shape=(), dtype=int32)


<class 'tensorflow.python.framework.ops.EagerTensor'>


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


<class 'tensorflow.python.framework.ops.EagerTensor'>


tf.Tensor(
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]], shape=(4, 4), dtype=int32)


<class 'tensorflow.python.framework.ops.EagerTensor'>


tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


<class 'tensorflow.python.framework.ops.EagerTensor'>


tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(5, 5), dtype=float32)


<class 'tensorflow.python.framework.ops.EagerTensor'>


tf.Tensor(
[[ 1.0593039   1.0217867   2.241534  ]
 [-0.42508805  2.8602548  -0.6381163 ]
 [-1.1328164   0.2800218  -0.27239665]], shape=(3, 3), dtype=float32)




#### 1.3. Math operations:

In [9]:
n1 = tf.constant(2)
n2 = tf.constant(3)
n3 = n1* n2

In [10]:
print(n3)

tf.Tensor(6, shape=(), dtype=int32)


In [11]:
n1 = tf.constant(4)
n2 = tf.constant(5)
n3 = tf.add(n1,n2)
print(n3)

tf.Tensor(9, shape=(), dtype=int32)


In [12]:
n1 = tf.constant(4)
n2 = tf.constant(5)
n3 = tf.multiply(n1,n2)
print(n3)

tf.Tensor(20, shape=(), dtype=int32)


In [13]:
n1 = tf.constant(2)
n2 = tf.constant(3)
n3 = tf.pow(n1,n2)
print(n3)

tf.Tensor(8, shape=(), dtype=int32)


#### 1.4. Matrix functions and operations:

In [14]:
m1 = tf.constant([[1,2], [3,4]])
m2 = tf.constant([[1], [2]])
m3 = tf.matmul(m1, m2)                            # Matrix multiplication. Different from the element-wise multiplication with multiply().
print(m3)

tf.Tensor(
[[ 5]
 [11]], shape=(2, 1), dtype=int32)


In [15]:
m1 = tf.constant([[1,2], [3,4]])
m2 = tf.constant([[5, 6], [7, 8]])
m3 = tf.matmul(m1, m2)
print(m3)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [16]:
m3 = tf.multiply(m1, m2)
print(m3)

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [17]:
m3 = m1*m2
print(m3)

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [18]:
m3 = m1 + m2
print(m3)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [19]:
m3 = m1-m2
print(m3)

tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)


In [20]:
m3 = m1 / m2
print(np.round(m3,3))

[[0.2   0.333]
 [0.429 0.5  ]]


In [21]:
# Matrix functions.
m = tf.constant([[1.0,2.0],[3.0,4.0]])
m_diagonal = tf.linalg.diag([1,2,3])
m_transpose = tf.linalg.matrix_transpose(m)
m_inverse = tf.linalg.inv(m)
m_multiplied = tf.matmul(m, m_inverse)
m_determinant = tf.linalg.det(m)
my_matrices = [m, m_diagonal, m_transpose, m_inverse, m_multiplied, m_determinant]
for mat in my_matrices:
    print(np.round(mat,3))
    print('\n')

[[1. 2.]
 [3. 4.]]


[[1 0 0]
 [0 2 0]
 [0 0 3]]


[[1. 3.]
 [2. 4.]]


[[-2.   1. ]
 [ 1.5 -0.5]]


[[ 1.  0.]
 [-0.  1.]]


-2.0




#### 1.5. TensorFlow Variable:

In [22]:
# Initializing Variables #1
x = tf.Variable(initial_value=5, name='x')       # Define.
y = tf.Variable(initial_value=6, name='y')       # Define.
f = (x - y)*y + 3                                # Define.
print(f)

tf.Tensor(-3, shape=(), dtype=int32)


In [23]:
# Initializing Variables #2
x = tf.Variable(initial_value=3, name='x')       # Define.
y = tf.Variable(initial_value=2, name='y')       # Define.
f = x*y + y + 3                                  # Define.
print(f)

tf.Tensor(11, shape=(), dtype=int32)
